# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-10 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='playing', through='movies.Role', to='movies.Person'),
        ),
    ]
